### ISSUE TITLE
Add multitask data to Makefile

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/deep_reference_parser#29]
Need to include

datasets = data/multitask/2020.3.18_multitask_train.tsv \
           data/multitask/2020.3.18_multitask_test.tsv \
           data/multitask/2020.3.18_multitask_valid.tsv \

in `datasets`

**Comment by ivyleavedtoadflax** [comment]
Ah good spot. I added them to S3://datalabs-public/deep_reference_parser/data/multitask/ (from memory) so it should just need the entry in the makefile, and nothing more.
